name: Merge Prod Into Main

on:
  push:
    branches:
      - 'prod'

jobs:
  main:
    name: Create PR Prod to Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      # Your other steps for creating a pull request

      # Assign reviewer surajn17
      - name: Assign Reviewer
        run: gh pr review --approve --body "Automated Approval" --comment "Automated Approval" --reviewer surajn17

      # Minimal status check example (replace with your actual CI/CD workflow)
      - name: Run CI Checks
        run: echo "Run your CI checks here"

      - name: enable automerge
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge
